import { LanguageId, LanguageProfile } from './types';

export const activeLanguageIds: LanguageId[] = [
  'typescript',
  'javascript',
  'python',
  'html',
  'css',
  'sql',
  'bash',
  'json',
  'yaml',
  'markdown',
];

export const preparedLanguageIds: LanguageId[] = [
  'go',
  'rust',
  'java',
  'csharp',
  'kotlin',
  'swift',
  'php',
  'ruby',
  'r',
  'dart',
  'lua',
  'cpp',
];

export const allLanguageIds: LanguageId[] = [...activeLanguageIds, ...preparedLanguageIds];

export const languageProfiles: Record<LanguageId, LanguageProfile> = {
  typescript: {
    id: 'typescript',
    label: 'TypeScript',
    supportLevel: 'active',
    summary: 'Base forte para aplicações React, Electron e sistemas com tipagem clara.',
    capabilities: ['ui', 'logic', 'tooling', 'documentation'],
    defaultUseCases: ['frontend', 'configuration', 'documentation'],
  },
  javascript: {
    id: 'javascript',
    label: 'JavaScript',
    supportLevel: 'active',
    summary: 'Superfície flexível para interação, scripts e integrações web.',
    capabilities: ['ui', 'logic', 'automation', 'tooling'],
    defaultUseCases: ['frontend', 'automation', 'scripting'],
  },
  python: {
    id: 'python',
    label: 'Python',
    supportLevel: 'active',
    summary: 'Rota preferencial para automação, processamento e futuras camadas de ML.',
    capabilities: ['automation', 'analysis', 'logic', 'tooling'],
    defaultUseCases: ['automation', 'data', 'backend'],
  },
  html: {
    id: 'html',
    label: 'HTML',
    supportLevel: 'active',
    summary: 'Materialização estrutural de superfícies editoriais e render premium.',
    capabilities: ['markup', 'documentation', 'ui'],
    defaultUseCases: ['markup', 'frontend', 'documentation'],
  },
  css: {
    id: 'css',
    label: 'CSS',
    supportLevel: 'active',
    summary: 'Composição visual, tema, respiro e controle fino de layout.',
    capabilities: ['styling', 'ui', 'markup'],
    defaultUseCases: ['styling', 'frontend'],
  },
  sql: {
    id: 'sql',
    label: 'SQL',
    supportLevel: 'active',
    summary: 'Consultas, integridade de dados e evolução de persistência.',
    capabilities: ['query', 'analysis', 'logic'],
    defaultUseCases: ['query', 'data', 'backend'],
  },
  bash: {
    id: 'bash',
    label: 'Bash / Shell',
    supportLevel: 'active',
    summary: 'Fluxos de build, scripts e automação operacional.',
    capabilities: ['automation', 'tooling', 'config'],
    defaultUseCases: ['automation', 'scripting'],
  },
  json: {
    id: 'json',
    label: 'JSON',
    supportLevel: 'active',
    summary: 'Dados, configuração e persistência leve do sistema.',
    capabilities: ['config', 'documentation', 'data'],
    defaultUseCases: ['configuration', 'data'],
  },
  yaml: {
    id: 'yaml',
    label: 'YAML',
    supportLevel: 'active',
    summary: 'Configuração legível, pipelines e manifestos técnicos.',
    capabilities: ['config', 'documentation'],
    defaultUseCases: ['configuration', 'documentation'],
  },
  markdown: {
    id: 'markdown',
    label: 'Markdown',
    supportLevel: 'active',
    summary: 'Documentação, relatórios e memória editorial.',
    capabilities: ['documentation', 'markup'],
    defaultUseCases: ['documentation', 'markup'],
  },
  go: { id: 'go', label: 'Go', supportLevel: 'prepared', summary: 'Preparado para serviços e CLI.', capabilities: ['logic', 'tooling'], defaultUseCases: ['backend', 'automation'] },
  rust: { id: 'rust', label: 'Rust', supportLevel: 'prepared', summary: 'Preparado para componentes de alta confiabilidade.', capabilities: ['logic', 'tooling'], defaultUseCases: ['backend', 'automation'] },
  java: { id: 'java', label: 'Java', supportLevel: 'prepared', summary: 'Preparado para ecossistemas empresariais.', capabilities: ['logic'], defaultUseCases: ['backend'] },
  csharp: { id: 'csharp', label: 'C#', supportLevel: 'prepared', summary: 'Preparado para apps e serviços em .NET.', capabilities: ['logic', 'ui'], defaultUseCases: ['backend'] },
  kotlin: { id: 'kotlin', label: 'Kotlin', supportLevel: 'prepared', summary: 'Preparado para Android e backend.', capabilities: ['logic'], defaultUseCases: ['backend'] },
  swift: { id: 'swift', label: 'Swift', supportLevel: 'prepared', summary: 'Preparado para ecossistemas Apple.', capabilities: ['ui', 'logic'], defaultUseCases: ['frontend'] },
  php: { id: 'php', label: 'PHP', supportLevel: 'prepared', summary: 'Preparado para aplicações web tradicionais.', capabilities: ['logic'], defaultUseCases: ['backend'] },
  ruby: { id: 'ruby', label: 'Ruby', supportLevel: 'prepared', summary: 'Preparado para automação e apps web.', capabilities: ['logic', 'automation'], defaultUseCases: ['backend', 'automation'] },
  r: { id: 'r', label: 'R', supportLevel: 'prepared', summary: 'Preparado para análise estatística.', capabilities: ['analysis'], defaultUseCases: ['data'] },
  dart: { id: 'dart', label: 'Dart', supportLevel: 'prepared', summary: 'Preparado para Flutter e superfícies multiplataforma.', capabilities: ['ui', 'logic'], defaultUseCases: ['frontend'] },
  lua: { id: 'lua', label: 'Lua', supportLevel: 'prepared', summary: 'Preparado para scripting leve.', capabilities: ['automation'], defaultUseCases: ['scripting'] },
  cpp: { id: 'cpp', label: 'C / C++', supportLevel: 'prepared', summary: 'Preparado para integrações nativas e alta performance.', capabilities: ['logic', 'tooling'], defaultUseCases: ['backend', 'automation'] },
};
